create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text,
  avatar_url text,
  app_role text not null default 'player' check (app_role in ('admin', 'player')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.games
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists join_code text,
  add column if not exists completed_at timestamptz;

create unique index if not exists games_join_code_idx on public.games (join_code) where join_code is not null;

create table if not exists public.game_memberships (
  id bigint generated by default as identity primary key,
  game_id text not null references public.games(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  membership_role text not null default 'player' check (membership_role in ('player', 'observer')),
  power_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (game_id, user_id),
  check (
    (membership_role = 'player' and power_key is not null)
    or (membership_role = 'observer' and power_key is null)
  )
);

create unique index if not exists game_memberships_game_power_key_idx
on public.game_memberships (game_id, power_key)
where power_key is not null;

create table if not exists public.player_private_state (
  player_id text primary key references public.players(id) on delete cascade,
  objective text not null,
  selected_action text not null,
  updated_at timestamptz not null default now()
);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'players'
      and column_name = 'objective'
  ) and exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'players'
      and column_name = 'selected_action'
  ) then
    insert into public.player_private_state (player_id, objective, selected_action)
    select id, objective, selected_action
    from public.players
    where objective is not null
    on conflict (player_id) do update
    set objective = excluded.objective,
        selected_action = excluded.selected_action,
        updated_at = now();
  end if;
end $$;

alter table public.players drop column if exists objective;
alter table public.players drop column if exists selected_action;

create or replace function public.generate_join_code()
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  candidate text;
begin
  loop
    candidate := upper(substring(md5(random()::text || clock_timestamp()::text) from 1 for 6));
    exit when not exists (
      select 1
      from public.games
      where join_code = candidate
    );
  end loop;

  return candidate;
end;
$$;

update public.games
set join_code = public.generate_join_code()
where join_code is null;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url, app_role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'avatar_url',
    case
      when lower(coalesce(new.email, '')) = 'sethlifland11@gmail.com' then 'admin'
      else 'player'
    end
  )
  on conflict (id) do update
  set email = excluded.email,
      full_name = coalesce(excluded.full_name, public.profiles.full_name),
      avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
      app_role = case
        when lower(coalesce(excluded.email, '')) = 'sethlifland11@gmail.com' then 'admin'
        else public.profiles.app_role
      end,
      updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.ensure_profile()
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  jwt_payload jsonb := auth.jwt();
  current_email text := lower(coalesce(jwt_payload ->> 'email', ''));
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  insert into public.profiles (id, email, full_name, avatar_url, app_role)
  values (
    current_user_id,
    current_email,
    coalesce(
      jwt_payload -> 'user_metadata' ->> 'full_name',
      jwt_payload -> 'user_metadata' ->> 'name'
    ),
    jwt_payload -> 'user_metadata' ->> 'avatar_url',
    case
      when current_email = 'sethlifland11@gmail.com' then 'admin'
      else 'player'
    end
  )
  on conflict (id) do update
  set email = excluded.email,
      full_name = coalesce(excluded.full_name, public.profiles.full_name),
      avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
      app_role = case
        when excluded.email = 'sethlifland11@gmail.com' then 'admin'
        else public.profiles.app_role
      end,
      updated_at = now();

  return current_user_id;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and app_role = 'admin'
  );
$$;

create or replace function public.can_access_game(target_game_id text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    auth.uid() is not null
    and (
      public.is_admin()
      or exists (
        select 1
        from public.game_memberships membership
        where membership.user_id = auth.uid()
          and membership.game_id = target_game_id
      )
      or exists (
        select 1
        from public.games game
        where game.id = target_game_id
          and game.created_by = auth.uid()
      )
    );
$$;

create or replace function public.can_access_player_private(target_game_id text, target_power_key text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    auth.uid() is not null
    and (
      public.is_admin()
      or exists (
        select 1
        from public.game_memberships membership
        where membership.user_id = auth.uid()
          and membership.game_id = target_game_id
          and membership.power_key = target_power_key
      )
      or exists (
        select 1
        from public.games game
        where game.id = target_game_id
          and game.created_by = auth.uid()
      )
    );
$$;

create or replace function public.create_game_with_defaults(game_name_input text, seat_power_key_input text default null)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  new_game_id text := 'game-' || substring(md5(random()::text || clock_timestamp()::text || coalesce(game_name_input, '')) from 1 for 12);
  requested_seat text := nullif(trim(seat_power_key_input), '');
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if trim(coalesce(game_name_input, '')) = '' then
    raise exception 'Game name is required';
  end if;

  perform public.ensure_profile();

  insert into public.games (id, name, round, event_index, status, created_by, join_code)
  values (
    new_game_id,
    trim(game_name_input),
    1,
    0,
    'active',
    current_user_id,
    public.generate_join_code()
  );

  insert into public.players (
    id,
    game_id,
    power_key,
    name,
    short_name,
    accent,
    role,
    home_class,
    capabilities,
    safety,
    market,
    support
  )
  select
    new_game_id || '-' || template.power_key,
    new_game_id,
    template.power_key,
    template.name,
    template.short_name,
    template.accent,
    template.role,
    template.home_class,
    template.capabilities,
    template.safety,
    template.market,
    template.support
  from public.players template
  where template.game_id = 'demo-game';

  insert into public.player_private_state (player_id, objective, selected_action)
  select
    new_game_id || '-' || template.power_key,
    private_state.objective,
    private_state.selected_action
  from public.players template
  join public.player_private_state private_state
    on private_state.player_id = template.id
  where template.game_id = 'demo-game';

  insert into public.player_cards (player_id, position, name, text)
  select
    new_game_id || '-' || template.power_key,
    card.position,
    card.name,
    card.text
  from public.players template
  join public.player_cards card
    on card.player_id = template.id
  where template.game_id = 'demo-game';

  insert into public.events (game_id, sort_order, title, text)
  select new_game_id, event.sort_order, event.title, event.text
  from public.events event
  where event.game_id = 'demo-game';

  insert into public.game_memberships (game_id, user_id, membership_role, power_key)
  values (
    new_game_id,
    current_user_id,
    case when requested_seat is null then 'observer' else 'player' end,
    requested_seat
  );

  return new_game_id;
end;
$$;

create or replace function public.join_game_by_code(join_code_input text, seat_power_key_input text default null)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  requested_code text := upper(trim(coalesce(join_code_input, '')));
  requested_seat text := nullif(trim(seat_power_key_input), '');
  target_game public.games%rowtype;
  current_membership public.game_memberships%rowtype;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if requested_code = '' then
    raise exception 'Join code is required';
  end if;

  perform public.ensure_profile();

  select *
  into target_game
  from public.games
  where join_code = requested_code
  limit 1;

  if target_game.id is null then
    raise exception 'No game found for join code %', requested_code;
  end if;

  if target_game.status <> 'active' then
    raise exception 'That game is not open for joining';
  end if;

  if requested_seat is not null and exists (
    select 1
    from public.game_memberships membership
    where membership.game_id = target_game.id
      and membership.power_key = requested_seat
      and membership.user_id <> current_user_id
  ) then
    raise exception 'That seat is already taken';
  end if;

  select *
  into current_membership
  from public.game_memberships
  where game_id = target_game.id
    and user_id = current_user_id
  limit 1;

  if current_membership.id is null then
    insert into public.game_memberships (game_id, user_id, membership_role, power_key)
    values (
      target_game.id,
      current_user_id,
      case when requested_seat is null then 'observer' else 'player' end,
      requested_seat
    );
  elsif requested_seat is not null then
    update public.game_memberships
    set membership_role = 'player',
        power_key = requested_seat,
        updated_at = now()
    where id = current_membership.id;
  end if;

  return target_game.id;
end;
$$;

create or replace function public.claim_game_seat(target_game_id_input text, target_power_key_input text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  normalized_power_key text := nullif(trim(target_power_key_input), '');
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if normalized_power_key is null then
    raise exception 'Seat selection is required';
  end if;

  if not exists (
    select 1
    from public.game_memberships membership
    where membership.game_id = target_game_id_input
      and membership.user_id = current_user_id
  ) then
    insert into public.game_memberships (game_id, user_id, membership_role, power_key)
    values (target_game_id_input, current_user_id, 'player', normalized_power_key);
  else
    if exists (
      select 1
      from public.game_memberships membership
      where membership.game_id = target_game_id_input
        and membership.power_key = normalized_power_key
        and membership.user_id <> current_user_id
    ) then
      raise exception 'That seat is already taken';
    end if;

    update public.game_memberships
    set membership_role = 'player',
        power_key = normalized_power_key,
        updated_at = now()
    where game_id = target_game_id_input
      and user_id = current_user_id;
  end if;

  return target_game_id_input;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists game_memberships_set_updated_at on public.game_memberships;
create trigger game_memberships_set_updated_at
before update on public.game_memberships
for each row execute function public.set_updated_at();

drop trigger if exists player_private_state_set_updated_at on public.player_private_state;
create trigger player_private_state_set_updated_at
before update on public.player_private_state
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.game_memberships enable row level security;
alter table public.player_private_state enable row level security;

drop policy if exists "profiles are readable to self or admin" on public.profiles;
create policy "profiles are readable to self or admin"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles are updated by admin" on public.profiles;
create policy "profiles are updated by admin"
on public.profiles for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "memberships are readable by self or admin" on public.game_memberships;
create policy "memberships are readable by self or admin"
on public.game_memberships for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "games are readable by authorized users" on public.games;
create policy "games are readable by authorized users"
on public.games for select
to authenticated
using (public.can_access_game(id));

drop policy if exists "games are insertable by creator or admin" on public.games;
create policy "games are insertable by creator or admin"
on public.games for insert
to authenticated
with check (created_by = auth.uid() or public.is_admin());

drop policy if exists "games are updateable by creator or admin" on public.games;
create policy "games are updateable by creator or admin"
on public.games for update
to authenticated
using (created_by = auth.uid() or public.is_admin())
with check (created_by = auth.uid() or public.is_admin());

drop policy if exists "games are deletable by creator or admin" on public.games;
create policy "games are deletable by creator or admin"
on public.games for delete
to authenticated
using (created_by = auth.uid() or public.is_admin());

drop policy if exists "players are readable by authorized users" on public.players;
create policy "players are readable by authorized users"
on public.players for select
to authenticated
using (public.can_access_game(game_id));

drop policy if exists "players are writable by admin" on public.players;
create policy "players are writable by admin"
on public.players for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "player private state is readable by owner or admin" on public.player_private_state;
create policy "player private state is readable by owner or admin"
on public.player_private_state for select
to authenticated
using (
  exists (
    select 1
    from public.players player
    where player.id = player_private_state.player_id
      and public.can_access_player_private(player.game_id, player.power_key)
  )
);

drop policy if exists "player private state is writable by admin" on public.player_private_state;
create policy "player private state is writable by admin"
on public.player_private_state for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "events are readable by authorized users" on public.events;
create policy "events are readable by authorized users"
on public.events for select
to authenticated
using (public.can_access_game(game_id));

drop policy if exists "events are writable by admin" on public.events;
create policy "events are writable by admin"
on public.events for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "player cards are readable by owner or admin" on public.player_cards;
create policy "player cards are readable by owner or admin"
on public.player_cards for select
to authenticated
using (
  exists (
    select 1
    from public.players player
    where player.id = player_cards.player_id
      and public.can_access_player_private(player.game_id, player.power_key)
  )
);

drop policy if exists "player cards are writable by admin" on public.player_cards;
create policy "player cards are writable by admin"
on public.player_cards for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

revoke all on public.games from anon, authenticated;
revoke all on public.players from anon, authenticated;
revoke all on public.player_cards from anon, authenticated;
revoke all on public.events from anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.game_memberships from anon, authenticated;
revoke all on public.player_private_state from anon, authenticated;

grant select, insert, update, delete on public.games to authenticated;
grant select, insert, update, delete on public.players to authenticated;
grant select, insert, update, delete on public.player_cards to authenticated;
grant select, insert, update, delete on public.events to authenticated;
grant select on public.profiles to authenticated;
grant select on public.game_memberships to authenticated;
grant select, insert, update, delete on public.player_private_state to authenticated;
grant usage, select on sequence public.game_memberships_id_seq to authenticated;
grant execute on function public.ensure_profile() to authenticated;
grant execute on function public.create_game_with_defaults(text, text) to authenticated;
grant execute on function public.join_game_by_code(text, text) to authenticated;
grant execute on function public.claim_game_seat(text, text) to authenticated;
